version: '3'
services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - '${PORT}:${PORT}'
    env_file: .env
    volumes:
      - './:${PATH_MOUNT}'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
