// auto-generated by typings-for-css-modules-loader
// See README for more info

declare namespace IndexModuleScssModule {
  export interface IIndexModuleScss {
    header: string;
  }
}

declare const IndexModuleScssModule: IndexModuleScssModule.IIndexModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: IndexModuleScssModule.IIndexModuleScss;
};

export = IndexModuleScssModule;
