// auto-generated by typings-for-css-modules-loader
// See README for more info

declare namespace LoadingModuleScssModule {
  export interface ILoadingModuleScss {
    loader: string;
    spin: string;
  }
}

declare const LoadingModuleScssModule: LoadingModuleScssModule.ILoadingModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LoadingModuleScssModule.ILoadingModuleScss;
};

export = LoadingModuleScssModule;
